import { useState } from "react";
import { motion } from "framer-motion";
import { C } from "../../constants/theme";

export default function LegalSection() {
  const [loading, setLoading] = useState(false);
  const [notice, setNotice] = useState(null);
  const [typedNotice, setTypedNotice] = useState("");
  const [target, setTarget] = useState("https://illegalstream.io/sports/clips/ufc_r45");

  const fullNotice = `DMCA TAKEDOWN NOTICE — AUTOMATED LEGAL INSTRUMENT
Generated by: SportGuard AI v2.6 · Gemini 2.5 Flash Engine
Asset ID: SG-2026-00847 · C2PA Record: sha256:a3f4bc9e21d7...
Timestamp: ${new Date().toUTCString()}

══════════════════════════════════════════════

TO: DMCA Agent — illegalstream.io / Hosting Provider
RE: Copyright Infringement Notice (17 U.S.C. § 512(c))

I, the undersigned, acting on behalf of the rights holder (UEFA Champions League Media B.V.), hereby notify you of copyright infringement on your platform.

INFRINGING CONTENT URL:
  ${target}

ORIGINAL WORK:
  UEFA Champions League Semi-Final Highlights (Matchday 29)
  Registration: TXu-2847-391 · Rights Territory: Global
  pHASH Similarity Score: 97.3% (threshold: 85%)

GOOD FAITH STATEMENT:
  I have a good faith belief that the use of the material described above is not authorized by the copyright owner, its agent, or the law. The information in this notification is accurate, and under penalty of perjury, I am authorized to act on behalf of the copyright owner.

REQUIRED ACTION:
  Immediate removal or disabling of access to the infringing content is required under 17 U.S.C. § 512(c)(1)(A).

CONTACT:
  SportGuard AI Legal Automation System
  legal@sportguard.ai · +1 (555) DMCA-000
  C2PA Provenance Chain: VERIFIED ✓

[DIGITAL SIGNATURE: 0xA3F4BC9E21D7BEEF]
`;

  const launch = () => {
    setLoading(true);
    setNotice(null);
    setTypedNotice("");
    setTimeout(() => {
      setLoading(false);
      setNotice(fullNotice);
      let i = 0;
      const tick = setInterval(() => {
        i++;
        setTypedNotice(fullNotice.slice(0, i * 3));
        if (i * 3 >= fullNotice.length) clearInterval(tick);
      }, 16);
    }, 1800);
  };

  return (
    <motion.section
      initial={{ opacity: 0, y: 50 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true, margin: "-100px" }}
      transition={{ duration: 0.5 }}
      id="legal"
      style={{ padding: "60px 40px", background: C.bg, borderBottom: `4px solid ${C.purple}` }}
    >
      <div style={{ marginBottom: "16px" }}><span className="tag tag-purple">AI LEGAL ENGINE</span></div>
      <h2 className="pixel" style={{ fontSize: "clamp(2rem,4vw,3rem)", margin: "0 0 8px", color: C.purple }}>
        #LEGAL — DMCA STRIKE TERMINAL
      </h2>
      <p className="mono" style={{ fontSize: "0.8rem", color: C.muted, margin: "0 0 40px" }}>
        Gemini 2.5 Flash drafts jurisdiction-aware DMCA notices with full C2PA evidence chains
      </p>

      <div style={{ display: "grid", gridTemplateColumns: "1fr 2fr", gap: "0" }}>
        <div style={{ border: `4px solid ${C.purple}`, padding: "24px", background: C.dark, borderRight: "none" }}>
          <div className="pixel" style={{ color: C.purple, fontSize: "1.1rem", marginBottom: "20px" }}>◈ STRIKE CONFIGURATION</div>
          <div style={{ marginBottom: "16px" }}>
            <div className="mono" style={{ fontSize: "0.7rem", color: C.muted, marginBottom: "6px" }}>INFRINGING URL</div>
            <input type="text" value={target} onChange={e => setTarget(e.target.value)} style={{ width: "100%" }} />
          </div>
          <div style={{ marginBottom: "16px" }}>
            <div className="mono" style={{ fontSize: "0.7rem", color: C.muted, marginBottom: "6px" }}>JURISDICTION</div>
            <select style={{ width: "100%", background: C.dark, color: C.text, border: `2px solid ${C.purple}`, padding: "8px", fontFamily: "'JetBrains Mono',monospace", fontSize: "0.8rem" }}>
              <option>United States (DMCA 512)</option>
              <option>European Union (DSA Art.16)</option>
              <option>United Kingdom (CDPA 1988)</option>
              <option>Global (Multi-jurisdictional)</option>
            </select>
          </div>
          <div style={{ marginBottom: "20px" }}>
            <div className="mono" style={{ fontSize: "0.7rem", color: C.muted, marginBottom: "6px" }}>ASSET ID</div>
            <input type="text" defaultValue="SG-2026-00847" style={{ width: "100%" }} />
          </div>
          <button className="btn-orange" style={{ width: "100%", marginBottom: "12px" }} onClick={launch}>
            {loading ? "◎ DRAFTING..." : "⚡ LAUNCH STRIKE"}
          </button>
          <button className="btn-ghost" style={{ width: "100%" }}>◈ SEND TO LEGAL TEAM</button>
          <div style={{ marginTop: "20px", border: `1px solid ${C.mid}`, padding: "12px" }}>
            <div className="mono" style={{ fontSize: "0.68rem", color: C.muted, lineHeight: 1.6 }}>
              <span style={{ color: C.purple }}>Model:</span> Gemini 2.5 Flash<br />
              <span style={{ color: C.purple }}>Mode:</span> Localized DMCA<br />
              <span style={{ color: C.purple }}>Evidence:</span> C2PA + pHASH<br />
              <span style={{ color: C.purple }}>Delivery:</span> Email + Certified
            </div>
          </div>
        </div>

        <div style={{ border: `4px solid ${C.purple}`, background: "#0A0A0A", padding: "0", position: "relative", overflow: "hidden" }}>
          <div style={{ background: C.purple, padding: "8px 16px", display: "flex", justifyContent: "space-between", alignItems: "center" }}>
            <span className="pixel" style={{ color: C.text, fontSize: "1rem" }}>GEMINI DMCA DRAFTING TERMINAL</span>
            <div style={{ display: "flex", gap: "8px" }}>
              {[C.red, C.yellow, C.green].map(c => <div key={c} style={{ width: 10, height: 10, background: c }} />)}
            </div>
          </div>
          <div style={{ padding: "20px", minHeight: "360px", fontFamily: "'JetBrains Mono',monospace", fontSize: "0.72rem", lineHeight: 1.6, overflowY: "auto", maxHeight: "440px" }}>
            <div style={{ color: C.green, marginBottom: "8px" }}>
              SportGuard@gemini-legal:~$ <span style={{ color: C.yellow }}>generate-dmca --model=gemini-2.5-flash --asset=SG-2026-00847</span>
            </div>
            {loading && (
              <div>
                <div style={{ color: C.purple }}>◎ Initialising Gemini 2.5 Flash model...</div>
                <div style={{ color: C.muted }}>◎ Fetching C2PA provenance chain...</div>
                <div style={{ color: C.muted }}>◎ Localising for jurisdiction: US DMCA §512...</div>
                <div style={{ color: C.yellow }}>◎ Drafting legal instrument<span className="blink">...</span></div>
              </div>
            )}
            {typedNotice && (
              <div style={{ color: C.text, whiteSpace: "pre-wrap", marginTop: "12px", borderTop: `1px solid ${C.purple}`, paddingTop: "12px" }}>
                {typedNotice}
                {typedNotice.length < fullNotice.length && <span className="blink">█</span>}
              </div>
            )}
            {!loading && !notice && (
              <div style={{ color: C.muted }}>// Configure parameters and click LAUNCH STRIKE<br />// Gemini 2.5 Flash will draft a localised DMCA notice<span className="blink terminal-cursor"></span></div>
            )}
          </div>
        </div>
      </div>
    </motion.section>
  );
}