import { useState, useEffect, useRef } from "react";
import { motion } from "framer-motion";
import { C } from "../../constants/theme";

// Note the prop is now matched to what we pass from App.jsx
export default function LegalSection({ target: incomingTarget }) {
  const [loading, setLoading] = useState(false);
  const [notice, setNotice] = useState(null);
  const [typedNotice, setTypedNotice] = useState("");
  const [target, setTarget] = useState("");
  const [jurisdiction, setJurisdiction] = useState("United States (DMCA 512)");
  const [sent, setSent] = useState(false);

  // NEW: Ref to track the bottom of the terminal for auto-scrolling
  const terminalEndRef = useRef(null);

  // Sync with Radar clicks & Auto-Launch
  useEffect(() => {
    if (incomingTarget) {
      setTarget(incomingTarget);
      // Smooth scroll to the terminal
      document.getElementById("legal")?.scrollIntoView({ behavior: "smooth" });
      // Automatically start drafting!
      launch(incomingTarget);
    }
  }, [incomingTarget]);

  // NEW: Auto-scroll terminal text as it types
  useEffect(() => {
    if (terminalEndRef.current) {
      terminalEndRef.current.scrollIntoView({ behavior: "smooth" });
    }
  }, [typedNotice]);

  const generateNotice = (activeTarget) => {
    const code = jurisdiction.includes("EU") ? "DSA Art.16" : jurisdiction.includes("UK") ? "CDPA 1988" : "17 U.S.C. § 512(c)";
    return `DMCA TAKEDOWN NOTICE — AUTOMATED LEGAL INSTRUMENT
Generated by: SportGuard AI v2.6 · Gemini 2.5 Flash Engine
Jurisdiction: ${jurisdiction}
Asset ID: SG-2026-00847 · C2PA Record: sha256:a3f4bc9e21d7...
Timestamp: ${new Date().toUTCString()}

══════════════════════════════════════════════

TO: DMCA Agent — Hosting Provider
RE: Copyright Infringement Notice (${code})

I, the undersigned, acting on behalf of the rights holder, hereby notify you of copyright infringement on your platform.

INFRINGING CONTENT URL:
  ${activeTarget}

GOOD FAITH STATEMENT:
  I have a good faith belief that the use of the material described above is not authorized by the copyright owner. Under penalty of perjury, I am authorized to act on behalf of the copyright owner.

CONTACT:
  SportGuard AI Legal Automation System
  legal@sportguard.ai
  C2PA Provenance Chain: VERIFIED ✓

[DIGITAL SIGNATURE: 0xA3F4BC9E21D7BEEF]
`;
  };

  const launch = (urlToUse = target) => {
    if (!urlToUse) return;
    setLoading(true);
    setNotice(null);
    setTypedNotice("");
    const fullNotice = generateNotice(urlToUse);

    setTimeout(() => {
      setLoading(false);
      setNotice(fullNotice);
      let i = 0;
      const tick = setInterval(() => {
        i++;
        setTypedNotice(fullNotice.slice(0, i * 4));
        if (i * 4 >= fullNotice.length) clearInterval(tick);
      }, 10);
    }, 1500);
  };

  return (
    <motion.section
      initial={{ opacity: 0, y: 50 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true, margin: "-100px" }}
      transition={{ duration: 0.5 }}
      id="legal"
      style={{ padding: "60px 40px", background: C.bg, borderBottom: `4px solid ${C.purple}` }}
    >
      <div style={{ marginBottom: "16px" }}><span className="tag tag-purple">AI LEGAL ENGINE</span></div>
      <h2 className="pixel" style={{ fontSize: "clamp(2rem,4vw,3rem)", margin: "0 0 8px", color: C.purple }}>
        #LEGAL — DMCA STRIKE TERMINAL
      </h2>
      <p className="mono" style={{ fontSize: "0.8rem", color: C.muted, margin: "0 0 40px" }}>
        Gemini 2.5 Flash drafts jurisdiction-aware DMCA notices with full C2PA evidence chains
      </p>

      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(300px, 1fr))", gap: "0" }}>
        <div style={{ border: `4px solid ${C.purple}`, padding: "24px", background: C.dark, borderRight: "none" }}>
          <div className="pixel" style={{ color: C.purple, fontSize: "1.1rem", marginBottom: "20px" }}>◈ STRIKE CONFIGURATION</div>
          <div style={{ marginBottom: "16px" }}>
            <div className="mono" style={{ fontSize: "0.7rem", color: C.muted, marginBottom: "6px" }}>INFRINGING URL</div>
            <input type="text" value={target} onChange={e => setTarget(e.target.value)} style={{ width: "100%" }} />
          </div>
          <div style={{ marginBottom: "16px" }}>
            <div className="mono" style={{ fontSize: "0.7rem", color: C.muted, marginBottom: "6px" }}>JURISDICTION</div>
            <select
              value={jurisdiction}
              onChange={(e) => setJurisdiction(e.target.value)}
              style={{ width: "100%", background: C.dark, color: C.text, border: `2px solid ${C.purple}`, padding: "8px", fontFamily: "'JetBrains Mono',monospace", fontSize: "0.8rem" }}
            >
              <option>United States (DMCA 512)</option>
              <option>European Union (DSA Art.16)</option>
              <option>United Kingdom (CDPA 1988)</option>
              <option>Global (Multi-jurisdictional)</option>
            </select>
          </div>
          <div style={{ marginBottom: "20px" }}>
            <div className="mono" style={{ fontSize: "0.7rem", color: C.muted, marginBottom: "6px" }}>ASSET ID</div>
            <input type="text" defaultValue="SG-2026-00847" style={{ width: "100%" }} />
          </div>
          <button className="btn-orange" style={{ width: "100%", marginBottom: "12px", opacity: loading ? 0.6 : 1 }} onClick={() => launch()} disabled={loading}>
            {loading ? "◎ DRAFTING NOTICE..." : "⚡ LAUNCH STRIKE"}
          </button>
          <button
            className="btn-ghost"
            style={{ width: "100%", borderColor: sent ? C.green : C.purple, color: sent ? C.green : C.text }}
            onClick={() => {
              setSent(true);
              setTimeout(() => setSent(false), 3000);
            }}
          >
            {sent ? "✓ DISPATCHED TO LEGAL" : "◈ SEND TO LEGAL TEAM"}
          </button>
        </div>

        <div style={{ border: `4px solid ${C.purple}`, background: "#0A0A0A", padding: "0", position: "relative", overflow: "hidden" }}>
          <div style={{ background: C.purple, padding: "8px 16px", display: "flex", justifyContent: "space-between", alignItems: "center" }}>
            <span className="pixel" style={{ color: C.text, fontSize: "1rem" }}>GEMINI DMCA DRAFTING TERMINAL</span>
            <div style={{ display: "flex", gap: "8px" }}>
              {[C.red, C.yellow, C.green].map(c => <div key={c} style={{ width: 10, height: 10, background: c }} />)}
            </div>
          </div>
          <div style={{ padding: "20px", minHeight: "360px", fontFamily: "'JetBrains Mono',monospace", fontSize: "0.72rem", lineHeight: 1.6, overflowY: "auto", maxHeight: "440px" }}>
            <div style={{ color: C.green, marginBottom: "8px" }}>
              SportGuard@gemini-legal:~$ <span style={{ color: C.yellow }}>generate-dmca --model=gemini-2.5-flash --asset=SG-2026-00847</span>
            </div>
            {loading && (
              <div className="mono">
                <div style={{ color: C.purple }}>◎ Initialising Gemini 2.5 Flash model...</div>
                <div style={{ color: C.muted }}>◎ Fetching C2PA provenance chain...</div>
                <div style={{ color: C.yellow }}>◎ Drafting legal instrument<span className="blink">...</span></div>
              </div>
            )}
            {typedNotice && (
              <div style={{ color: C.text, whiteSpace: "pre-wrap", marginTop: "12px", borderTop: `1px solid ${C.purple}`, paddingTop: "12px" }}>
                {typedNotice}
                {typedNotice.length < (notice?.length || 0) && <span className="blink">█</span>}
              </div>
            )}
            {!loading && !notice && (
              <div style={{ color: C.muted }}>// Configure parameters and click LAUNCH STRIKE<br />// Gemini 2.5 Flash will draft a localised DMCA notice</div>
            )}

            {/* NEW: This invisible div tracks the bottom of the text for the auto-scroll */}
            <div ref={terminalEndRef} />

          </div>
        </div>
      </div>
    </motion.section>
  );
}